import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

// ─────────────────────────────────────────────────────────────
// POST INTERFACE
// Matches your existing posts table + 4 new columns added
// by the migration. All new fields are optional so existing
// code that doesn't set them continues to work unchanged.
// ─────────────────────────────────────────────────────────────
export interface Post {
  // ── Existing columns (unchanged) ──────────────────────────
  id?:               string;      // uuid, auto-generated by Supabase
  title:             string;      // required
  slug:              string;      // required, unique
  content?:          string;
  excerpt?:          string;
  created_at?:       string;
  updated_at?:       string;
  author?:           string;
  tags?:             string[];
  views?:            number;      // default 0
  category?:         string;
  referral_links?:   ReferralLink[];
  is_published?:     boolean;     // default false
  meta_title?:       string;
  meta_description?: string;
  focus_keyword?:    string;

  // ── New columns (added by migration.sql) ──────────────────
  schema_json_ld?:   string;      // Schema.org NewsArticle JSON-LD
  reading_time_min?: number;      // estimated reading time in minutes
  model_used?:       string;      // 'gpt-4o' | 'gpt-4o-mini'
  ai_quality_score?: number;      // 0-100 score from quality gate
}

export interface ReferralLink {
  url:  string;
  type: 'airdrop' | 'external' | 'referral' | 'unknown';
}

// ─────────────────────────────────────────────────────────────
// SUPABASE CLIENT
// ─────────────────────────────────────────────────────────────
const supabaseUrl = process.env.SUPABASE_URL!;
const supabaseKey = process.env.SUPABASE_SERVICE_KEY!; // service role — bypasses RLS

if (!supabaseUrl || !supabaseKey) {
  throw new Error('[supabase] Missing SUPABASE_URL or SUPABASE_SERVICE_KEY in .env');
}

export const supabase = createClient(supabaseUrl, supabaseKey);